### ISSUE TITLE
Question: What is the purpose of surrogate, tau_div? 

### ISSUE THREAD

**Issue by AranBSmith** [resibots/map_elites_hexapod_v2#5]
Hi,

Posting here as I could not find anything on this with the sferes2 wiki, what is the purpose of surrogate in the EA here?

I was also hoping if you could help explain if there is a relationship between tau_div = 0.05, epsilon = 0.05, and the sampled sferes array being spaced by 0.05.

**Comment by costashatz** [comment]
Hey,

This is left-overs from copy-pasting. Nothing to do with MAP-Elites or the hexapod.. Thanks for catching this.
